# OS: Windows; Symfony: latest stable; PHP: latest stable
name: "Tests - Windows"

on:
    pull_request:
    push:
        branches:
            - 'master'

env:
    fail-fast: true

jobs:
    tests:
        runs-on: 'windows-latest'
        continue-on-error: false
        steps:
            - name: 'Checkout code'
              uses: actions/checkout@v2.3.3

            - name: 'Install PHP with extensions'
              uses: shivammathur/setup-php@v2
              with:
                  coverage: none
                  php-version: '8.1'
                  tools: composer:v2
                  extensions: mbstring, intl
                  ini-values: date.timezone=UTC

            - name: 'Install project dependencies'
              env:
                  SYMFONY_REQUIRE: 6.2
              run: |
                  composer update --no-interaction --prefer-dist --optimize-autoloader --prefer-stable
                  vendor/bin/simple-phpunit install
            - name: 'Run tests'
              env:
                  SYMFONY_DEPRECATIONS_HELPER: 'max[indirect]=10&max[total]=27'
              run: vendor/bin/simple-phpunit -v