# OS: Windows; Symfony: latest stable; PHP: latest stable
name: "Tests - Windows"

on:
    pull_request:
    push:
        branches:
            - 'master'

env:
    fail-fast: true

jobs:
    tests:
        runs-on: 'windows-latest'
        continue-on-error: false
        strategy:
          matrix:
            php-version: [ '8.1' ]
            symfony-version: [ '6.2' ]
        steps:
            - name: 'Checkout code'
              uses: actions/checkout@v3

            - name: 'Install PHP with extensions'
              uses: shivammathur/setup-php@v2
              with:
                  coverage: none
                  php-version: ${{ matrix.php-version }}
                  tools: composer:v2
                  extensions: mbstring, intl
                  ini-values: date.timezone=UTC

            - name: 'Install project dependencies'
              run: |
                  composer config extra.symfony.require "${{ matrix.symfony-version }}"
                  composer update --no-interaction --prefer-dist --optimize-autoloader --prefer-stable
                  vendor/bin/simple-phpunit install
            - name: 'Run tests'
              env:
                  SYMFONY_DEPRECATIONS_HELPER: 'max[indirect]=10&max[total]=27'
              run: vendor/bin/simple-phpunit -v